nts do you need to enter for first list: "<<endl;
    // int c;
    // cin>>c;
    // linkedlist* first=create_linked_list(c);
    // cout<<"how many elements do you need to enter for second list: "<<endl;
    // int d;
    // cin>>d;
    // linkedlist* second=create_linked_list(d);
    // linkedlist* l=merge_sort_merge(first,second);
    // traversal(l);